### ISSUE TITLE
Revise and re-release

### ISSUE THREAD

**Issue by JJ** [raku-community-modules/MIME-Types#8]
If at all possible.

**Comment by camstuart** [comment]
Indeed, a `zef install MIME::Types` currently fails, and is a dependency on https://github.com/Raku/examples/issues/75

I am happy to assist if you can provide guidance

**Comment by JJ** [comment]
El sáb., 29 ago. 2020 a las 5:00, Cam Stuart (<notifications@github.com>)
escribió:

> Indeed, a zef install MIME::Types currently fails, and is a dependency on
> Raku/examples#75 <https://github.com/Raku/examples/issues/75>
>
> I am happy to assist if you can provide guidance
>

Well, it needs a pretty extensive overhaul. I've added a few issues to
start... Thanks.

**Comment by lizmat** [comment]
I've done an overhaul earlier today.  Please let me know if more needs to be done.
